# Generated by Django 4.1.2 on 2022-12-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_discound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discound',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='option',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Children', 'Children')], max_length=10, null=True),
        ),
    ]
