# Generated by Django 4.1.3 on 2022-12-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_orderplaced_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='longitude',
        ),
    ]
