# Generated by Django 4.1.3 on 2022-12-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_orderplaced_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='country',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='county',
        ),
    ]
