# Generated by Django 4.1.3 on 2022-12-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_orderplaced_product_orderplaced_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='address',
            field=models.CharField(default='exit', max_length=100, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='post_code',
            field=models.CharField(default='exit', max_length=8, verbose_name='Post Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='town',
            field=models.CharField(default='exit', max_length=100, verbose_name='Town/City'),
            preserve_default=False,
        ),
    ]
