# Generated by Django 4.1.3 on 2022-12-08 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_orderplaced_phone_number_alter_orderplaced_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='cart',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='product',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
