# Generated by Django 4.1.3 on 2022-12-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_orderplaced_product_orderplaced_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='town',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='address2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='country',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='first_name',
            field=models.CharField(default='exit', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='last_name',
            field=models.CharField(default='exit', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='state',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='zip_code',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
