# Generated by Django 4.1.3 on 2022-12-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_remove_orderplaced_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
