# Generated by Django 4.1.3 on 2022-12-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(blank=True, choices=[('tm', 'The request was successful'), ('dr', 'Delivery is underway'), ('sdh', 'sent delivered handed')], max_length=3),
        ),
    ]
