# Generated by Django 4.1.3 on 2022-12-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_orderplaced_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
