# Generated by Django 4.1.3 on 2022-12-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscribe'),
        ('store', '0034_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='address_order',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='address2_order',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='country_order',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='email_order',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='first_name_order',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='last_name_order',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='quantity_order',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='state_order',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='status_order',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='timestamp_order',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='updated_order',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='zip_code_order',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='orders',
        ),
        migrations.AddField(
            model_name='sales',
            name='user_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
