# Generated by Django 4.1.3 on 2022-12-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_rename_address_order_sales_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orderplaced'),
        ),
    ]
