# Generated by Django 4.1.3 on 2022-12-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_sales_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='order_item',
        ),
    ]
