# Generated by Django 4.1.3 on 2022-12-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_sales_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
