# Generated by Django 4.1.3 on 2022-12-03 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_is_buyer'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='captcha_score',
        ),
        migrations.RemoveField(
            model_name='account',
            name='post_code',
        ),
        migrations.AddField(
            model_name='account',
            name='logo',
            field=models.ImageField(default='accounts/logo.png', upload_to='accounts'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(default='ezit', max_length=100, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='county',
            field=models.CharField(max_length=100, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='account',
            name='latitude',
            field=models.CharField(default='exit', max_length=50, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='longitude',
            field=models.CharField(default='exit', max_length=50, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='town',
            field=models.CharField(default='exit', max_length=100, verbose_name='Town/City'),
            preserve_default=False,
        ),
    ]
