# Generated by Django 4.1.3 on 2022-12-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_brief_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Brief',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='exit', max_length=254),
            preserve_default=False,
        ),
    ]
